-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "vatId" TEXT NOT NULL DEFAULT '48156bcc-e71b-48c6-8520-88b74b223676';

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_vatId_fkey" FOREIGN KEY ("vatId") REFERENCES "Vat"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
